### PR TITLE
Created new repo for saltswap code (previously misname 'constant salt')

### PR DESCRIPTION
**Pull request by gregoryross**
@jchodera @bas-rustenburg I've created a new repo specifically for what was previously call 'constant salt' (although the number of salt pairs was not constant!). I've done this for greater visibility, more specific documentation, and the fact that, for the moment, these are two separate projects.

### CODE REVIEW

**Comment by jchodera** [comment]
Sounds good!

Aside from deciding on an API for MCMC blocks, the major changes that it looks like we would want to make here are:
* Retrieve salt parameters from a `ForceField` object instead of pulling them from a `System/Topology`, in case we want to start with a box with no salt in it yet.
* Move from discrete parameter updates to the ability to do continuous parameter updates to allow us to switch between water and salt with NCMC (as in the [fractional titration states in `openmm-constph`](https://github.com/choderalab/openmm-constph/blob/master/constph/constph.py#L804-L875)
* Implement NCMC switching

**Comment by gregoryross** [comment]
- At the moment, the anion and cation parameters are hard coded into the `SaltSwap` class, but pulling them from a `forcefield` object sounds more flexible.
- Adding NCMC moves is next on only list to do. Current acceptance rates are hovering around 5%, and NCMC seems like a great way to adapt water to newly inserted ions.

**Comment by jchodera** [comment]
> Adding NCMC moves is next on only list to do. Current acceptance rates are hovering around 5%, and NCMC seems like a great way to adapt water to newly inserted ions.

+1!  That's essentially what NCMC was designed for!

**Comment by gregoryross** [comment]
Would you both mind confirming that I have the correct acceptance test for insertion and deletion of salt? Particularly, that I've correctly accounted for the proposal probability in `attempt_identity_swap`. Currently:
- I choose whether to insert or delete salt with a 50% probability, except when there is no salt, or all salt. When not at the boundaries, this choice is symmetric and does not enter into the acceptance test. I have not accounted for the cases when there is no salt or all salt, so I think I need to include a factor of 1/2 in the acceptance test for these cases.
- If I am inserting salt, I pick two water molecules without replacement. If N_wat, N_cat, N_ani are the current number of waters, cations and anions respectively, the proposal probability for this selection is 1/(N_wat*(N_wat-1)). In the reverse move, I would select an cation and anion (for which there are one more of each) without replacement, so the proposal probability would be 1/((N_cat+1)*(N_ani+1)). I then include the ratio of reverse to forward proposals probabilities in the acceptance test.
- Similarly for deleting salt.

Does that sound correct? Thanks!

**Comment by jchodera** [comment]
Sorry to not have seen this earlier!  Checking it out now!

**Comment by jchodera** [comment]
> I choose whether to insert or delete salt with a 50% probability, except when there is no salt, or all salt. When not at the boundaries, this choice is symmetric and does not enter into the acceptance test. I have not accounted for the cases when there is no salt or all salt, so I think I need to include a factor of 1/2 in the acceptance test for these cases.

That's correct.  You need to ensure that the Metropolis-Hastings acceptance criteria includes
```
P(old | new)
------------
P(new | old)
```
which means if `P(new | old) = 1` because you were at one of the boundaries, but `P(old | new) = 0.5`, then this ratio is either 0.5 or 2.

**Comment by jchodera** [comment]
> If I am inserting salt, I pick two water molecules without replacement. If N_wat, N_cat, N_ani are the current number of waters, cations and anions respectively, the proposal probability for this selection is 1/(N_wat*(N_wat-1)). In the reverse move, I would select an cation and anion (for which there are one more of each) without replacement, so the proposal probability would be 1/((N_cat+1)*(N_ani+1)). I then include the ratio of reverse to forward proposals probabilities in the acceptance test.

This sounds correct to me!

**Comment by gregoryross** [comment]
Great, thanks.

**Pull request merged**
